//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Collection_And_Supply.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodRequest
    {
        public int Id { get; set; }
        public string FoodName { get; set; }
        public int FamilyMember { get; set; }
        public string Discription { get; set; }
        public string Status { get; set; }
        public string City { get; set; }
        public int FkUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
