//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Collection_And_Supply.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodCollectionDBEntities : DbContext
    {
        public FoodCollectionDBEntities()
            : base("name=FoodCollectionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DonatedFood> DonatedFoods { get; set; }
        public virtual DbSet<FoodRequest> FoodRequests { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
